version: "2"
services:
  web:
    container_name: web
    environment:
      DEBUG_PORT: '0.0.0.0:28283'
      LOG_LEVEL: info
    ports:
      - '28283:28283'
    extends:
      file: docker-compose.base.yaml
      service: web
    build:
      context: ./services/web
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
        NODE_ENV: "${MODE}"
        REPOSITORY_SERVER: ${REPOSITORY_SERVER}
    command: node --inspect=0.0.0.0:28283 index.js
    links:
      - mongodb
  mongodb:
    extends:
      file: docker-compose.base.yaml
      service: mongodb
    volumes:
      - ./data:/data/db
networks:
  multicontainer_network:
    driver: bridge