version: "2"
services:
  web:
    container_name: web
    #restart: always
    environment:
      DB_SERVER: "${DB_SERVER}"
      DB_DATABASE: "${DB_DATABASE}"
      PORT: "${PORT}"
      NODE_ENV: "${MODE}"
    ports:
      - "${PORT}:${PORT}"
    networks:
      - multicontainer_network  
  mongodb:
    container_name: mongodb
    image: mongo
    #restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - multicontainer_network
    